### ISSUE TITLE
Maybe use github issue templates

### ISSUE THREAD

**Issue by anandthakker** [hotosm/oam-uploader#1]
Maybe this can help: https://github.com/kentcdodds/issue-template

**Comment by smit1678** [comment]
Instead of using issue-template service, we can do a light template and url encode creating a new ticket: 

https://github.com/hotosm/oam-uploader-admin/issues/new?title=New%20Token--[NAME]&body=Please%20send%20me%20a%20new%20token

Closing out and will use this method for now.
