### ISSUE TITLE
Token in status page

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-uploader#14]
@ricardomestre Status page is looking great. Do we want to include the token as part of the general information section? Was there a reason for including it? I'm thinking that maybe it's less useful information and may be a little insecure to show publicly.

**Comment by ricardoduplos** [comment]
Thanks for the feedback @smit1678. I don't think there's a good reason to include the token info. I did some cosmetic changes in the meantime, and also the token is gone.

cc/ @anandthakker

**Comment by smit1678** [comment]
Dig it. Looks good. :rocket:

**Comment by anandthakker** [comment]
Good call on removing the token -- in fact, that information wouldn't (shouldn't) be available from the API anyway, since we decided to make the upload status unauthenticated.
