### ISSUE TITLE
Design mockup

### ISSUE THREAD

**Issue by ricardoduplos** [hotosm/oam-uploader#2]
## Structure
- Logo
- Explanatory text about how to use and become an uploader. Links to more info (on GitHub?)
- Upload form
## Upload form
- Token key
- Uploader info
  - Name
  - Email (mandatory)
- scene info: 
  - Contact info (tick to use the former)
    - Name
    - Email (mandatory)
  - provider
  - platform
  - sensor
  - acquisition_start
  - acquisition_end
  - Tile service (if available)
  - Imagery URLs (text area, one per line)
- Note on the imagery license agreement
- Submit
### UX
- Form inline validation
- Success / Failure message on form submission

**Comment by smit1678** [comment]
To recap our conversation, we're going to proceed with a "scene" based grouping. A scene may be a single capture that is split into smaller images. A scene may be a single image file. A scene may also be a mosaic of several scenes or images together that have then been split into separate images. 

Additional scene group information: 
- contact -- name and email
- provider -- Provider/owner of the OIN bucket
- platform -- List of possible platform sources limited to satellite, aircraft, UAV, balloon, kite
- sensor -- How the data was collected? (image acquisition device... camera, radar, ...)
- acquisition_start -- First date of acquisition in UTC (Combined date and time representation)
- acquisition_end -- Last date of acquisition in UTC (Combined date and time representation). Can be same as start if a single time capture. 
- Tile service (if available)

Edited in above list.

**Comment by anandthakker** [comment]
Let's add a `title` field to each scene as well

**Comment by anandthakker** [comment]
And maybe _also_ a `description` field?  So someone can add a few notes about the drone flight they're uploading, for example...  cc @smit1678
