### ISSUE TITLE
Add check box for license agreement

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-uploader#23]
As [it is still not 100% agreed](https://lists.openstreetmap.org/pipermail/legal-talk/2015-July/008159.html) that CC-BY 4.0 is compatible with OSM's ODBL, I propose to include an explicit check box for the uploader to click and confirm that the imagery is traceable in OSM.

See also https://github.com/openimagerynetwork/oin-register/issues/4

Original attribution will be preserved in each OIN file, and also when that image or image set from the same contributor is published separately as an OAM tile service. It will convert to OIN's CC-BY 4.0 license once it gets published as a mixed tile service.

@lossyrob @smit1678 @wonderchook and @cholmes please confirm this approach.

**Comment by smit1678** [comment]
@cgiovando We could do a checkbox, but would it be just fine to say something that combines both? A statement that you agree upon by submitting.

**Comment by smit1678** [comment]
Something along these lines? 

> By submitting imagery to OpenAerialMap, you agree to place your imagery into the Open Imagery Network (OIN). All imagery contained in OIN is licensed CC-BY 4.0, with attribution as contributors of Open Imagery Network. All imagery is available to be traced in OpenStreetMap.

This could go here: 

![openaerialmap uploader 2015-09-11 16-24-49](https://cloud.githubusercontent.com/assets/796838/9825501/abe80a8a-58a1-11e5-864f-1a3a83c8892b.png)
