### ISSUE TITLE
How to get a token

### ISSUE THREAD

**Issue by danielfdsilva** [hotosm/oam-uploader#3]
Document how users can get a token.

Proposed process:
- Open an issue explaining what kind of imagery they have available.
- Add label `label name`.
- Admin will review and send token via email.

**Comment by scisco** [comment]
@danielfdsilva how does admin get the email of the requester?

**Comment by danielfdsilva** [comment]
We discussed this and we've 2 options:
- The requester shares his email on the issue.
  or
- The requester emails the admin (on a public email.)

**Comment by smit1678** [comment]
@danielfdsilva Could the github issue template referenced from #1 could be useful here?

**Comment by smit1678** [comment]
Drafted some notes related to getting a token: https://gist.github.com/smit1678/b281540a39b45ccf9520. Here's how we're seeing the process thus far: 

## How to get a token
1. Go to upload.openaerialmap.org
2. Select documentation link or click on link next to Token
3. Modal pops up - If Github account, create a ticket (autofilled), if not send email (autofilled)
4. Fill out Github issue or email
   - fill in template
   - tag label in github
5. Token will then be sent to you via email

#### Template to fill in:

```
Name: 
Email: 
Location of imagery: 
Source of imagery: 
Short description of collection:
Have you received approval for making this imagery available (yes/no)?:
```

Thinking behind some of these questions is to get more information related to the imagery and how it was collected -- ensure adhering to best practices especially UAV collected imagery. 

@cgiovando -- additions to the steps or changes to the questions?
