### ISSUE TITLE
Upload error code 23

### ISSUE THREAD

**Issue by Stefal** [hotosm/oam-uploader#78]
Hello,
I tried to upload an aerial geotiff, from my local nas, or from a server, and I always receive an error code 23:

> Upload failed: Exited with 23: Downloading http://www.stemani.fr/sevre.tif

The geotiff's size is 7.8 GB and I can open it with Qgis without problem.
What is wrong ?

upload status id : 593b95a0e407d70011386121

**Comment by smit1678** [comment]
@Stefal Thanks for posting the issue. We're looking into it. At first glance it's not clear what the issue is - perhaps something timed out. Can you attempt to retry the https://nas.stemani.fr/sevre.tif url again? 

Posting the full error code here for reference: 

```
170610/070353.302, [log,worker,worker 593b95,error], data: {"message":"Exited with 23: 
Downloading http://www.stemani.fr/sevre.tif...\n","stack":"Error: Exited with 23: Downloading
 http://www.stemani.fr/sevre.tif...\n\n    at ChildProcess.<anonymous> (/app/worker/process-
image.js:84:24)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:191:7)\n    at 
Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)"}
```

**Comment by Stefal** [comment]
@smit1678 I relaunched the upload process (id 5940047de407d70011386144) with the same result.

**Comment by tombh** [comment]
@Stefal we've made some changes on the server, can you try again please.

**Comment by Stefal** [comment]
I'm sorry @tombh, it still fail (id 59496e1f6b41170011e189c1)

**Comment by tombh** [comment]
Thanks for that. I've got one step further at least and now the image downloads correctly - it was just a problem with our new server's `/tmp` config. But now there's a new problem during conversion! This is both frustrating and helpful - handling large imagery is absolutely something we need to easily support, so fixing these bugs is essential for us.

**Comment by tombh** [comment]
Il est fixe! Et voila: https://upload.openaerialmap.org/#/status/59496e1f6b41170011e189c1
Un peu Francais pour un moment parce que je l'apprend. Je peux voir une riviere tres belle :) Le lien à  l'image sur la carte: https://map.openaerialmap.org/#/-1.1314804868751827,47.0303864307312,11/0313313100110/59522ebbb0eae7f3b1440024?_k=scdkdk

Technical notes about the problems found:
1. The server setup had at some point changed to start using `tmpfs` which forced a 4GB limit on uploads.
2. `TMPDIR` was no longer set inside Docker. I have temporarily hard coded it in `process.sh` whilst I look into the problem more.
3. The 1 hour timeout was being hit during the `gdaladdo` overviews step. I have temporarily hardcoded 2 hour timeouts whilst we think of a better solution. /cc @mojodna

**Comment by Stefal** [comment]
Merci @tombh ! Et bon courage pour l'apprentissage du français. D'ailleurs, pour ma part, je devrais réouvrir l'application Duolingo pour améliorer mon anglais.

Thank you for your work. I hope I will upload more aerial pictures next year.
btw: is there a way to get a permalink with tms enabled ?

**Comment by tombh** [comment]
Merci, j'utilise Duolingo aussi!

Oui, il y a permalink à le TMS, mais ce n'est pas documenté https://tiles.openaerialmap.org/59496e1f6b41170011e189c1/0/e7b5069e-a7f0-44cd-967c-2e88eaf5e576/preview

On en train de discuter le meilleur facon lier ceci sur le website.
