### ISSUE TITLE
Document the process of getting a token

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-uploader#8]
Start with outline of steps for requesting a token

**Comment by danielfdsilva** [comment]
The process of getting a token is pretty much outlined https://github.com/hotosm/oam-uploader/issues/3

Next steps:
- [ ] Polish text.
- [ ] Decide where to put it and make link to it from the "Read documentation" link on the uploader.
- [ ] Decide what repo/email should get the token requests and update the link on the uploader.
