### ISSUE TITLE
16 bit GeoTIFF imagery - Background (value = 0) not transparent

### ISSUE THREAD

**Issue by fabiogt** [hotosm/oam-uploader#83]
Despite correctly processed and uploaded, the background (pixel value = 0) of 16 bit imagery (GeoTIFF with LZW compression) is not properly flagged as transparent.

**Comment by smit1678** [comment]
@fabiogt Do you have an example or link to the image with the issue?

**Comment by fabiogt** [comment]
@smit1678 it should be https://map.openaerialmap.org/#/upload/status/5ac4f84326964b001003310f?_k=x84lq6

**Comment by smit1678** [comment]
thanks @fabiogt. Can you explain what would be ideal here? I'm seeing edges as transparent: 

![openaerialmap browser 2018-04-05 09-53-17](https://user-images.githubusercontent.com/796838/38356255-2c975706-38b7-11e8-8760-17fa4b69d6f4.png)

**Comment by fabiogt** [comment]
Hi @smit1678 , this is a different image (forced to 8 bit) with respect to the one linked. FYI: I deleted all the uploaded images with issues, leaving only the successful one.
The linked one appeared like this:
![image](https://user-images.githubusercontent.com/38096632/38357009-a6f91944-38c1-11e8-987c-64a715979e60.png)

**Comment by smit1678** [comment]
Great, thanks, this helpful information. 

From the 16-bit image, at first glance it does not look like there was a no-data value set: 

```
Band 1 Block=17646x1 Type=UInt16, ColorInterp=Red
Band 2 Block=17646x1 Type=UInt16, ColorInterp=Green
Band 3 Block=17646x1 Type=UInt16, ColorInterp=Blue
```

But in the 8-bit image, it was set: 

```
Band 1 Block=128x128 Type=Byte, ColorInterp=Red
  NoData Value=65536
  Metadata:
    SourceBandIndex=0
Band 2 Block=128x128 Type=Byte, ColorInterp=Green
  NoData Value=65536
  Metadata:
    SourceBandIndex=1
Band 3 Block=128x128 Type=Byte, ColorInterp=Blue
  NoData Value=65536
  Metadata:
    SourceBandIndex=2
```

This may have a factor but would need to test to confirm. 

cc @mojodna

**Comment by fabiogt** [comment]
Thanks for checking/testing!
The background pixels in the 8-bit image should actually be (0,0,0), since I understood that the zero value would have been automatically interpreted as transparent background (this is also related to https://github.com/hotosm/oam-docs/issues/47)

**Comment by sethfitz** [comment]
NODATA strikes again.

`65536` is an invalid 8-bit value, but it ends up being treated as `0` by GDAL / rasterio (I think; marblecutter may also be making that assumption).

If you can, the best solution for transparency is to either include an alpha band (explicit transparency, but sometimes problematic when creating overviews) or a mask band (similar to an alpha band but equivalent to marking pixels w/ NODATA values explicitly). A mask band would be best, but I'm not sure about the best approach for creating one.

**Comment by fabiogt** [comment]
Thanks for the details: unfortunately it is not clear how to handle this operationally.
An additional issue is that setting 0 to transparent leads to have also the shadowed/darker areas in the image flagged as transparent.
From an OAM user perspective, the best solution in my opinion would be to have the possibility to set the background values during the upload. 

![image](https://user-images.githubusercontent.com/38096632/39856921-ecd35e8a-5431-11e8-8861-e5d7f0712038.png)
