### ISSUE TITLE
After uploading and succesfull processing image didn't show anywhere (in catalog, on map, in profile...)

### ISSUE THREAD

**Issue by sergeyastakhov** [hotosm/oam-uploader#84]
After uploading and succesfull processing image didn't show anywhere (in recent images, on map, in profile...).
For example:
https://map.openaerialmap.org/#/upload/status/5ad1d26d91b5310010e0d503
https://map.openaerialmap.org/#/upload/status/5ad29c2891b5310010e0d50a (repeat of previous)
https://map.openaerialmap.org/#/upload/status/5ad383c291b5310010e0d511

Last successful upload, that normaly shows on the map was 12 April

**Comment by smit1678** [comment]
@sergeyastakhov Looking into this and will report back.
